# Generated by Django 5.1.6 on 2026-06-10 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('COMMERCIAL', 'Commercial Space'), ('LAND', 'Land / Plot'), ('TOWNHOUSE', 'Townhouse')], default='APARTMENT', max_length=20)),
                ('status', models.CharField(choices=[('RENT', 'To Let'), ('SALE', 'For Sale')], default='RENT', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(help_text='e.g. Juja, Westlands, Milimani', max_length=100)),
                ('bedrooms', models.IntegerField(default=0, verbose_name='Bedrooms (0 for Land)')),
                ('bathrooms', models.IntegerField(default=0, verbose_name='Bathrooms')),
                ('parking_spaces', models.IntegerField(default=0, verbose_name='Parking Spaces')),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list, e.g. Borehole, Backup Generator, Gym')),
                ('main_image', models.ImageField(upload_to='properties/thumbnails/')),
                ('maps_iframe_url', models.TextField(blank=True, help_text='Paste the src link inside the Google Maps embed code iframe')),
                ('is_featured', models.BooleanField(default=False, help_text='Pin this property to the homepage featured grid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='property.property')),
            ],
        ),
    ]
